@extends('layouts.pos')
@section('title', $reservation->reservation_code)
@section('content')
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="d-flex justify-content-between align-items-start"><div><h1>{{ $reservation->reservation_code }}</h1>@include('partials.reservation-status-badge', ['status' => $reservation->status])</div><a class="btn btn-outline-secondary" href="{{ route('pos.reservations.index') }}">{{ __('reservation.internal.back') }}</a></div>
    <dl class="row mt-4"><dt class="col-sm-3">{{ __('reservation.fields.customer') }}</dt><dd class="col-sm-9">{{ $reservation->customer->name }} · {{ $reservation->customer->phone }}</dd><dt class="col-sm-3">{{ __('reservation.fields.date_time') }}</dt><dd class="col-sm-9">{{ $reservation->reservation_date->format('d/m/Y') }} {{ substr($reservation->reservation_time, 0, 5) }}</dd><dt class="col-sm-3">{{ __('reservation.fields.party_size') }}</dt><dd class="col-sm-9">{{ $reservation->party_size }}</dd><dt class="col-sm-3">{{ __('reservation.fields.note') }}</dt><dd class="col-sm-9">{{ $reservation->note ?: '—' }}</dd><dt class="col-sm-3">{{ __('reservation.fields.table') }}</dt><dd class="col-sm-9">{{ $reservation->table ? $reservation->table->code.' — '.$reservation->table->name : __('reservation.internal.not_assigned') }}</dd><dt class="col-sm-3">{{ __('reservation.internal.confirmed_by') }}</dt><dd class="col-sm-9">{{ $reservation->confirmedBy?->name ?: '—' }}</dd></dl>
    <div class="d-flex flex-wrap gap-2">@if($reservation->status === \App\Enums\ReservationStatus::Pending)<form method="post" action="{{ route('pos.reservations.confirm', $reservation) }}">@csrf @method('patch')<button class="btn btn-success">{{ __('reservation.internal.confirm') }}</button></form><form method="post" action="{{ route('pos.reservations.reject', $reservation) }}">@csrf @method('patch')<button class="btn btn-outline-danger">{{ __('reservation.internal.reject') }}</button></form>@endif @if($reservation->status === \App\Enums\ReservationStatus::Confirmed && auth()->user()->can('reservation.mark-no-show'))<form method="post" action="{{ route('pos.reservations.mark-no-show', $reservation) }}">@csrf @method('patch')<button class="btn btn-outline-secondary">{{ __('reservation.internal.mark_no_show') }}</button></form>@endif</div>
    @if($reservation->status === \App\Enums\ReservationStatus::Confirmed && auth()->user()->can('reservation.manage') && auth()->user()->can('dining-session.open') && auth()->user()->can('table.operate'))
        <form class="card card-body mt-4" method="post" action="{{ route('pos.reservations.check-in', $reservation) }}">@csrf
            <label class="form-label" for="table_id">{{ __('dining_session.select_table') }}</label>
            <div class="d-flex gap-2"><select class="form-select" id="table_id" name="table_id" required><option value="">{{ __('dining_session.select_table') }}</option>@foreach($availableTables as $table)<option value="{{ $table->id }}">{{ $table->code }} — {{ $table->name }} ({{ $table->capacity }}){{ $table->location ? ' · '.$table->location : '' }}</option>@endforeach</select><button class="btn btn-primary" @disabled($availableTables->isEmpty())>{{ __('dining_session.check_in') }}</button></div>
            @if($availableTables->isEmpty())<small class="text-danger mt-2">{{ __('dining_session.errors.no_suitable_table') }}</small>@endif
        </form>
    @endif
    @if($reservation->diningSession && auth()->user()->can('dining-session.view'))<p class="mt-4"><a class="btn btn-outline-primary" href="{{ route('pos.dining-sessions.show', $reservation->diningSession) }}">{{ __('dining_session.view_session', ['code' => $reservation->diningSession->session_code]) }}</a></p>@endif
@endsection
