@extends('layouts.pos')
@section('title', __('billing.invoice').' '.$bill->bill_code)
@section('content')
<style media="print">nav,.btn{display:none!important} main{padding:0!important}</style>
<div class="d-flex justify-content-between"><h1>{{ __('billing.invoice') }}</h1><button class="btn btn-outline-primary" onclick="window.print()">{{ __('billing.print') }}</button></div>
<dl class="row"><dt class="col-sm-4">{{ __('billing.bill_code') }}</dt><dd class="col-sm-8">{{ $bill->bill_code }}</dd><dt class="col-sm-4">{{ __('billing.session') }}</dt><dd class="col-sm-8">{{ $bill->diningSession->session_code }}</dd><dt class="col-sm-4">{{ __('billing.table') }}</dt><dd class="col-sm-8">{{ $bill->diningSession->table->code }} — {{ $bill->diningSession->table->name }}</dd><dt class="col-sm-4">{{ __('billing.customer') }}</dt><dd class="col-sm-8">{{ $bill->diningSession->customer?->name ?? __('dining_session.anonymous') }}</dd></dl>
@include('pos.billing._items')
<dl class="row"><dt class="col-sm-4">{{ __('billing.subtotal') }}</dt><dd class="col-sm-8">{{ number_format($bill->subtotal, 0, ',', '.') }} ₫</dd><dt class="col-sm-4">{{ __('billing.voucher') }}</dt><dd class="col-sm-8">{{ $bill->voucher?->code ?? '—' }}</dd><dt class="col-sm-4">{{ __('billing.discount') }}</dt><dd class="col-sm-8">{{ number_format($bill->discount_amount, 0, ',', '.') }} ₫</dd><dt class="col-sm-4">{{ __('billing.total') }}</dt><dd class="col-sm-8"><strong>{{ number_format($bill->total_amount, 0, ',', '.') }} ₫</strong></dd><dt class="col-sm-4">{{ __('billing.method') }}</dt><dd class="col-sm-8">{{ __('billing.methods.'.$bill->successfulPayment->method) }}</dd><dt class="col-sm-4">{{ __('billing.reference') }}</dt><dd class="col-sm-8">{{ $bill->successfulPayment->transaction_reference ?: '—' }}</dd><dt class="col-sm-4">{{ __('billing.paid_at') }}</dt><dd class="col-sm-8">{{ $bill->successfulPayment->paid_at->format('d/m/Y H:i') }}</dd><dt class="col-sm-4">{{ __('billing.processed_by') }}</dt><dd class="col-sm-8">{{ $bill->successfulPayment->processedBy->name }}</dd></dl>
@endsection
