@csrf
@if ($product->exists) @method('put') @endif
<div class="mb-3"><label class="form-label" for="category_id">{{ __('app.categories.title') }}</label><select class="form-select @error('category_id') is-invalid @enderror" id="category_id" name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id', $product->category_id) === (string) $category->id)>{{ $category->name }}</option>@endforeach</select>@error('category_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="mb-3"><label class="form-label" for="name">{{ __('app.fields.name') }}</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $product->name) }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="mb-3"><label class="form-label" for="slug">{{ __('app.fields.slug') }}</label><input class="form-control @error('slug') is-invalid @enderror" id="slug" name="slug" value="{{ old('slug', $product->slug) }}" required>@error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="mb-3"><label class="form-label" for="description">{{ __('app.fields.description') }}</label><textarea class="form-control" id="description" name="description" rows="4">{{ old('description', $product->description) }}</textarea></div>
<div class="mb-3"><label class="form-label" for="image_url">{{ __('app.fields.image_url') }}</label><input type="url" class="form-control" id="image_url" name="image_url" value="{{ old('image_url', $product->image_url) }}"></div>
@unless($product->exists)<div class="mb-3"><label class="form-label" for="price">{{ __('app.fields.price') }}</label><input type="number" min="0" class="form-control @error('price') is-invalid @enderror" id="price" name="price" value="{{ old('price', 0) }}" required>@error('price')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@endunless
<div class="row"><div class="col-md-6 mb-3"><label class="form-label" for="status">{{ __('app.fields.status') }}</label><select class="form-select" id="status" name="status"><option value="active" @selected(old('status', $product->status ?? 'active') === 'active')>{{ __('app.statuses.active') }}</option><option value="inactive" @selected(old('status', $product->status) === 'inactive')>{{ __('app.statuses.inactive') }}</option></select></div><div class="col-md-6 mb-3"><label class="form-label" for="is_available">{{ __('app.fields.availability') }}</label><select class="form-select" id="is_available" name="is_available"><option value="1" @selected((string) old('is_available', $product->is_available ?? true) === '1')>{{ __('app.products.available') }}</option><option value="0" @selected((string) old('is_available', $product->is_available ?? true) === '0')>{{ __('app.products.unavailable') }}</option></select></div></div>
<button class="btn btn-primary">{{ __('app.save') }}</button>
